language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
sudo: false
install:
- pip install -r requirements.txt
- pip install coveralls
- pip freeze
script: nosetests
after_success: coveralls
deploy:
  provider: pypi
  user: BYPyPi
  password:
    secure: MHNvzUDHGS7SQdPxvZL+gayv6RVTNADZspXltt4eyiC3/xo8qTRuABfU2mNVJHtaxxEd7mSGoNHxsJUEPrU2CeDnD6JW760FdqCvGr5uARYkxoJhAAF8hfpUL7Y7XU1bdNVj/naxjLmPD5WayeWWPGObtiP1xnkxwydpCSFYGlM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
  
